VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Company"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Id As String
Public Name As String
Public DisplayName As String
Public Phone As String
Public AddressLine As String
Public AddressLine2 As String
Public City As String
Public State As String
Public Zip As String
Public Industry As String
Public Size As String
Public Producer As String
Public ConfigurationName As String
Public Custom1 As String
Public Custom2 As String
Public Custom3 As String
Public Custom4 As String
Public Custom5 As String



