VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Config"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Id As String
Public BrokerId As String
Public BrokerName As String
Public Key As String
Public Name As String
Public Description As String
Public Active As Boolean
Public Master As Boolean


