VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "User"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Id As String
Public FirstName As String
Public LastName As String
Public CompanyName As String
Public Email As String
Public Username As String
Public JobTitle As String
Public Phone As String
Public Department As String
Public Role As String
Public Custom1 As String
Public Custom2 As String
Public Custom3 As String
Public Custom4 As String
Public CompanyId As String

